apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.depName }}
  namespace: wso2is
  labels:
    deployment: wso2is # Labels for the deployment itself
spec:
  replicas: 2
  selector:
    matchLabels:
      deployment: wso2is  # Selector labels to match labels in the pod template
  template:
    metadata:
      labels:
        deployment: wso2is  # Labels applied to pods created by this template
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
            - containerPort: 4000
            - containerPort: 9763
            - containerPort: 3306
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts: 
            - name: identity-server-conf
              mountPath: /home/wso2carbon/wso2is-7.0.0/repository/conf/deployment.toml
              subPath: deployment.toml

      volumes:
        - name: identity-server-conf
          configMap:
            name: identity-server-conf
      serviceAccountName: is-service-account