apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace : wso2is
  labels:
    deployment: wso2is
spec:
  type: LoadBalancer
  selector:
    deployment: wso2is
  ports:  
  - name: servlet-http
    port: 9763
    targetPort: 9763
    protocol: TCP
  - name: servlet-https
    port: 9443
    targetPort: 9443
    protocol: TCP