apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wso2is
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      deployment: mysql
      pod: wso2is
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        deployment: mysql
        pod: wso2is
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 999
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: regadmin
            - name: MYSQL_PASSWORD
              value: regadmin
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            # - name: mysql-persistent-storage
            #   mountPath: /var/lib/mysql
            - name: mysql-dbscripts
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        # - name: mysql-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: mysql-pv-claim
        - name: mysql-dbscripts
          configMap:
            name: mysql-dbscripts
