apiVersion: apps/v1
kind: Deployment
metadata:
  name: is-deployment
  labels:
    app: is
spec:
  replicas: 1
  selector:
    matchLabels:
      app: is
  template:
    metadata:
      labels:
        app: is
    spec:
      containers:
        - name: is
          image: is6.1
          imagePullPolicy: Never
          ports:
            - containerPort: 9443

