apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.depName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: is6.1
          imagePullPolicy: Never
          ports:
            - containerPort: 9443

