apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serName }}
spec:
  type: NodePort
  selector:
    app: is
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30100