apiVersion: apps/v1
kind: Deployment
metadata:
  name: is-deployment
  labels:
    app: is
spec:
  replicas: 1
  selector:
    matchLabels:
      app: is
  template:
    metadata:
      labels:
        app: is
    spec:
      containers:
        - name: is
          image: is6.1
          imagePullPolicy: Never
          ports:
            - containerPort: 9443

---
apiVersion: v1
kind: Service
metadata:
  name: is-service
spec:
  type: NodePort
  selector:
    app: is
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30100